apiVersion: v1
kind: Pod
metadata:
  name: namespace-mon
spec:
  restartPolicy: Never
  serviceAccountName: namespace-viewer  
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do curl -s --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes/api/v1/namespaces; sleep 5; done']
