apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox:stable
      command: ['sh', '-c', 'echo $DB-USERNAME; echo $DB-PASSWORD; echo $DB-PORT; echo $APP-PORT"]
