apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: features.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: features
    singular: feature
    kind: Feature
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              new_ui:
                type: boolean
              beta:
                type: boolean
