apiVersion: v1
kind: Pod
metadata:
  name: cache-pod
spec:
  securityContext:
    runAsUser: 4050
    runAsGroup: 4050
    fsGroupChangePolicy: "OnRootMismatch"
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']
    volumeMounts:
    - mountPath: /var/cache
      name: cache-volume
    securityContext:
      capabilities:
        drop: ["NET_ADMIN", "SYS_TIME"]        
  volumes:
    - name: cache-volume
      emptyDir: {}
