apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sjakson
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: klink
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: kadmin
